### ISSUE TITLE
Sample charts

### ISSUE THREAD

**Issue by fulljackz** [35niavlys/dokuwiki-plugin-amcharts#5]
Hi there,

Thanks for your plugin !

Would you update your doc with some samples such as xy or steps charts pls ?

It would be aweome.

Cheers

**Comment by 35niavlys** [comment]
Hi and and thank you for your interest.
This plugin is a simple wrapper of the amcharts library, so the best documentation is the library documentation and this one is very well documented ;)
For example in order to create a xy chart, you can refer to the source of this demo : https://www.amcharts.com/demos/xy-chart-fills-axis/

Cheers
